baseURL = "https://devynharrington.com/"
title = "Devyn Harrington"
theme = "blowfish"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params]
  customCSS = ["css/custom.css"]
  
  [params.search]
    enable = true 
  # Homepage profile layout (circle avatar above name)
  [params.homepage]
    layout = "profile"
    showRecent = false
    recentLimit = 3

    [params.homepage.profile]
      imageWidth = 300
      imageHeight = 300
      imageQuality = 100

  # Favicon configuration
  [params.favicon]
    ico = "favicon.ico"
    png = "favicon-32x32.png"
    apple = "apple-touch-icon.png"

  [params.author]
    name = "Devyn Harrington"
    image = "img/profile.jpg"
    headline = "Senior VCF Consultant | DoD Infrastructure | MS Cybersecurity & MBA | Marine Corps Veteran"

    links = [
      { linkedin = "https://www.linkedin.com/in/devynharrington" },
      { github = "https://github.com/devynharrington" },
    ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "VCF"
    url = "/vcf/"
    weight = 3
