baseURL = "https://devynharrington.com/"
title = "Devyn Harrington"
theme = "blowfish"

[params]
  customCSS = ["css/custom.css"]

  # Homepage profile layout (circle avatar above name)
  [params.homepage]
    layout = "profile"

    [params.homepage.profile]
      imageWidth = 300
      imageHeight = 300
      imageQuality = 100

  # Favicon configuration
  [params.favicon]
    ico = "favicon.ico"
    png = "favicon-32x32.png"
    apple = "apple-touch-icon.png"

  [params.author]
    name = "Devyn Harrington"
    image = "img/profile.jpg"
    headline = "Senior VCF Consultant | DoD Infrastructure | MS Cybersecurity & MBA | Marine Corps Veteran"

    links = [
      { linkedin = "https://www.linkedin.com/in/devynharrington" },
      { github = "https://github.com/devynharrington" },
      { link = "https://www.credly.com/users/devyn-harrington" }
    ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true